# Generated by Django 4.0.1 on 2022-01-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120)),
                ('price', models.PositiveIntegerField(default=100)),
                ('product_image', models.ImageField(null=True, upload_to='images')),
                ('location', models.CharField(max_length=120)),
            ],
        ),
    ]
